In [37]:
import pandas as pd
import numpy as np

In [38]:
df_train = pd.read_csv('C:/Users/srija/Documents/DS_Predict_TelecomChurn/data/training_data.csv')

In [39]:
df_train.head()

Unlimited_Data  Streaming_TV  Streaming_Music  Streaming_Movies  \
0               1             0                0                 0   
1               1             0                0                 0   
2               1             1                1                 1   
3               1             0                0                 0   
4               1             0                0                 0   

   Premium_Tech_Support  Number_of_Referrals  Tenure_in_Months  Total_Charges  \
0                     0                    1                57        1061.60   
1                     0                    8                16        1321.30   
2                     1                    0                 4         396.30   
3                     0                    0                 4          84.75   
4                     0                    0                16        1043.30   

   Monthly_Charge  Total_Long_Distance_Charges  Customer_Status  
0           19.40                      2368.92                0  
1           80.75                       736.00                0  
2           98.10                        22.52                1  
3           20.40                       128.60                0  
4           69.65                       366.40                0

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_train.drop(['Customer_Status'],axis=1), 
                                                    df_train['Customer_Status'], test_size=0.10, 
                                                    random_state=101)

In [41]:
from sklearn.metrics import classification_report,confusion_matrix

### Logistic Regression

In [42]:
from sklearn.linear_model import LogisticRegression

In [43]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

C:\Users\srija\Documents\DS_Predict_TelecomChurn\venv1\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [44]:
predictions = logmodel.predict(X_test)
predictions

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [45]:
print(confusion_matrix(y_test,predictions))

[[290  40]
 [ 65  56]]


In [46]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85       330
           1       0.58      0.46      0.52       121

    accuracy                           0.77       451
   macro avg       0.70      0.67      0.68       451
weighted avg       0.75      0.77      0.76       451



### Decision Tree

In [47]:
from sklearn.tree import DecisionTreeClassifier

dt_model=DecisionTreeClassifier()
dt_model.fit(X_train,y_train)

dt_pred = dt_model.predict(X_test)

print(confusion_matrix(y_test,dt_pred))

[[269  61]
 [ 46  75]]


In [48]:
print(classification_report(y_test,dt_pred))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83       330
           1       0.55      0.62      0.58       121

    accuracy                           0.76       451
   macro avg       0.70      0.72      0.71       451
weighted avg       0.77      0.76      0.77       451



### Random Forest

In [49]:
from sklearn.ensemble import RandomForestClassifier

rf= RandomForestClassifier(n_estimators=500)
rf.fit(X_train,y_train)

rf_pre=rf.predict(X_test)

print(confusion_matrix(y_test,rf_pre))

[[290  40]
 [ 54  67]]


In [50]:
print(classification_report(y_test,rf_pre))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       330
           1       0.63      0.55      0.59       121

    accuracy                           0.79       451
   macro avg       0.73      0.72      0.72       451
weighted avg       0.78      0.79      0.79       451



### XgBoost

In [51]:
from xgboost import XGBClassifier
xgboost = XGBClassifier(n_estimators=1000)
xgboost.fit(X_train,y_train)

xg_pred = xgboost.predict(X_test)

In [52]:
print(confusion_matrix(y_test,xg_pred))

[[276  54]
 [ 52  69]]


In [53]:
print(classification_report(y_test,xg_pred))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84       330
           1       0.56      0.57      0.57       121

    accuracy                           0.76       451
   macro avg       0.70      0.70      0.70       451
weighted avg       0.77      0.76      0.77       451



### ANN

In [54]:
import keras 
from keras.layers import Dense
from keras.models import Sequential

In [55]:
ann  = Sequential()
ann.add(Dense(units= 32, activation = 'relu', input_dim=10))
ann.add(Dense(units= 32, activation = 'relu'))
ann.add(Dense(units= 1, activation = 'sigmoid'))
ann.compile(optimizer='adam',
              loss='mean_squared_error',
              metrics=['accuracy'])

In [56]:
ann.fit(X_train,y_train, epochs=300,verbose= 0)

In [57]:
ann_pred = ann.predict(X_test)
ann_pred = [ 1 if y>=0.5 else 0 for y in ann_pred]
print(ann_pred)

15/15 [==============================] - 0s 670us/step
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,

In [58]:
print(confusion_matrix(y_test,ann_pred))

[[276  54]
 [ 56  65]]


In [59]:
print(classification_report(y_test,ann_pred))

              precision    recall  f1-score   support

           0       0.83      0.84      0.83       330
           1       0.55      0.54      0.54       121

    accuracy                           0.76       451
   macro avg       0.69      0.69      0.69       451
weighted avg       0.75      0.76      0.76       451



In [60]:
import pickle
# open a file, where you ant to store the data
file = open('C:/Users/srija/Documents/DS_Predict_TelecomChurn/data/decision_tree_classification_model.pkl', 'wb')

# dump information to that file
pickle.dump(rf, file)